workflows:
  android-capacitor:
    name: Android Capacitor Build
    max_build_duration: 60

    environment:
      node: 22
      java: 21
      android_signing:
        - bafnatoys_android_release

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @capacitor/cli

      - name: Create .env file
        script: |
          echo "VITE_API_URL=https://bafnatoys-backend-production.up.railway.app/api" > .env
          echo "VITE_API_BASE_URL=https://bafnatoys-backend-production.up.railway.app/api" >> .env
          echo "VITE_IMAGE_BASE_URL=https://bafnatoys-backend-production.up.railway.app" >> .env
          echo "VITE_SOCKET_URL=https://bafnatoys-backend-production.up.railway.app" >> .env
          echo "VITE_RAZORPAY_KEY=rzp_live_S81sOEbV1qBfkK" >> .env

      - name: Build web app
        script: |
          npm run build

      - name: Capacitor sync
        script: |
          npx cap sync android

      - name: Fix gradlew permission
        script: |
          cd android
          chmod +x gradlew

      - name: Build Android AAB and APK
        script: |
          cd android
          ./gradlew bundleRelease
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk