workflows:
  android-capacitor:
    name: Android Capacitor Build
    max_build_duration: 60

    environment:
      node: 22
      java: 21  # <--- YE LINE SABSE ZAROORI HAI!
      android_signing:
        - bafnatoys_android_release

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @capacitor/cli

      - name: Build web app
        script: |
          npm run build

      - name: Capacitor sync
        script: |
          npx cap sync android

      - name: Fix gradlew permission
        script: |
          cd android
          chmod +x gradlew

      - name: Build Android AAB
        script: |
          cd android
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk