workflows:
  android-capacitor:
    name: Android Capacitor Build
    max_build_duration: 60

    environment:
      node: 22

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build web app
        script: |
          npm run build

      - name: Capacitor sync
        script: |
          npx cap sync android

      - name: Build Android (AAB)
        script: |
          cd android
          ./gradlew bundleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
