workflows:
  android-capacitor:
    name: Android Capacitor Build
    max_build_duration: 60
    environment:
      node: 18
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install

      - name: Build web app
        script: |
          cd frontend
          npm run build

      - name: Capacitor sync
        script: |
          cd frontend
          npx cap sync android

      - name: Build Android
        script: |
          cd frontend/android
          ./gradlew bundleRelease
